server.port=8083
spring.application.name=Pricing

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/pricingdb
spring.datasource.username=postgres
spring.datasource.password=945845
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Circuit Breaker
resilience4j.circuitbreaker.instances.pricingService.sliding-window-size=10
resilience4j.circuitbreaker.instances.pricingService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.pricingService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.pricingService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.pricingService.automatic-transition-from-open-to-half-open-enabled=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
